fix:added the email validator
arteevraina/KnowYourDonor pull request #36
Opened 2021-02-14 07:35 UTC by avishmehta68710

2021-02-14 07:54 UTC, avishmehta68710 commented
can you tell me why my pr checks are failing this time i did everything which you mentioned earlier

2021-02-16 13:54 UTC, arteevraina commented
> can you tell me why my pr checks are failing this time i did everything which you mentioned earlier

@avishmehta68710 seems like some formatting issues with the code. But, still I think we can merge this PR after slight changes.

2021-02-16 13:55 UTC, arteevraina requested changes

2021-02-16 13:55 UTC, arteevraina commented on lib/constants/validators.dart
> +  bool isValid = RegExp(email).hasMatch(emailaddress);
rename this variable as `emailAddress`. Follow camelCasing for naming variables :)

2021-02-16 13:56 UTC, arteevraina commented
Also it is a good practice to write what the code does in PR description.

2021-02-17 08:45 UTC, avishmehta68710 commented
Hi 
Please check now i have applied the changes but still getting this error

2021-02-17 13:09 UTC, arteevraina approved these changes

2021-02-17 13:09 UTC, arteevraina commented
@avishmehta68710 LGTM!

2021-02-17 13:10 UTC, merged